name: solr
icon: solr
type: search
title: Solr
hostname: solr
containers:
- name: solr
  image: wodby/solr
  ports:
  - name: solr
    number: 80
    type: http
options:
- version: '9.5.0'
scalable: false
labels:
- solr

kubernetes:
  infrastructure:
  - name: operator
    title: Solr Operator
    service: solr-operator
    version: '9.5.0'

helm:
  name: apache-solr
  source: https://solr.apache.org/charts
  chart: apache-solr/solr
  version: v0.8.0
  values: 
  - name: 'zk.address'
    value: '{{links.zookeeper.host}}'

links:
- name: zookeeper
  title: ZooKeeper
  required: true
  selectors:
  - type: datastore
    labels:
    - zookeeper
