name: solr
icon: solr
type: search
title: Solr
hostname: solr
containers:
- name: solr
  image: wodby/solr
  env:
  - name: ZK_HOST
    value: '{{links.zookeeper.host}}'
  - name: SOLR_CLOUD_PASSWORD
    value: '{{password}}'
# make sure Kubernetes env var overridden with correct value to not break health check
  - name: SOLR_PORT
    value: 8983

options:
- version: '9'
  tag: '9.10'
endpoints:
- name: solr
  ports:
  - name: solr
    number: 8983
    type: http
    main: true
labels:
- solr

helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/solr
  chart: oci://registry-1.docker.io/wodby/solr
  version: 0.1.0
  configurations:
  - name: solr
    labels: podLabels
    annotations: podAnnotations
    env: envVars
    resources: resources

links:
- name: zookeeper
  title: ZooKeeper
  required: true
  selectors:
  - type: datastore
    labels:
    - zookeeper

tokens:
- name: password
  generate:
    regex: '[0-9a-z-]{32}'  

volumes:
- name: data
  title: Data
  optional: true
  size: 5
  helm: 
    labels: commonLabels
    values:
    - name: persistence.enabled
      value: true
    - name: persistence.size
      value: '{{volumes.data.size}}Gi'
