name: solr
icon: solr
type: search
title: Solr
hostname: solr
containers:
- name: solr
  image: bitnami/solr

env: 
- name: DISABLE_WELCOME_MESSAGE
  value: '1'
options:
- version: '9'
  tag: '9.6.0-debian-12-r0'
endpoints:
- name: solr
  ports:
  - name: solr
    number: 8983
    type: http
    main: true
labels:
- solr

helm:
  name: bitnamicharts
  source: oci://registry-1.docker.io/bitnamicharts/solr
  chart: oci://registry-1.docker.io/bitnamicharts/solr
  version: 9.1.3
  configurations:
  - name: solr
    labels: podLabels
    annotations: podAnnotations
    env: extraEnvVars
    resources: resources
  values: 
  - name: auth.adminPassword
    value: '{{password}}'
  - name: zookeeper.enabled
    value: false
  - name: externalZookeeper.servers
    value: ['{{links.zookeeper.host}}']
  - name: resourcesPreset
    value: 'none'
  - name: collectionReplicas
    value: '{{service.replicas}}'
  - name: collection
    value: default

links:
- name: zookeeper
  title: ZooKeeper
  required: true
  selectors:
  - type: datastore
    labels:
    - zookeeper

tokens:
- name: password
  generate:
    regex: '[0-9a-z-]{32}'  

volumes:
- name: data
  title: Data
  optional: true
  size: 5
  helm: 
    labels: commonLabels
    values:
    - name: persistence.enabled
      value: true
    - name: persistence.size
      value: '{{volumes.data.size}}Gi'
