name: solr
icon: solr
type: search
title: Solr
hostname: solr
containers:
- name: solr
  image: wodby/solr
  ports:
  - name: solr
    number: 80
    type: http
    main: true    
options:
- version: '9.5.0'
labels:
- solr

kubernetes:
  infrastructure:
  - name: operator
    title: Solr Operator
    service: solr-operator
    version: '9.5.0'

helm:
  name: apache-solr
  source: https://solr.apache.org/charts
  chart: apache-solr/solr
  version: v0.8.0
  configuration:
    labels: statefulSetOptions.labels
    annotations: statefulSetOptions.annotations
    env: podOptions.envVars
  values: 
  - name: 'zk.address'
    value: '{{links.zookeeper.host}}'
  - name: 'pullPolicy'
    value: '{{pullPolicy}}' 

links:
- name: zookeeper
  title: ZooKeeper
  required: true
  selectors:
  - type: datastore
    labels:
    - zookeeper

volumes:
- name: data
  title: Data
  optional: true
  size: 5
  helm: 
    values:
    - name: dataStorage.type
      value: persistent
    - name: dataStorage.capacity
      value: '{{volumes.data.size}}Gi'
    - name: dataStorage.persistent.reclaimPolicy
      value: Delete

