name: solr
icon: solr
type: search
title: Solr
options:
- version: '9'
  tag: '9.10'
endpoints:
- name: solr
  ports:
  - name: solr
    number: 8983
    protocol: http
    main: true
labels:
- solr

helm:
  name: wodby
  source: oci://registry-1.docker.io/wodby/solr
  chart: oci://registry-1.docker.io/wodby/solr
  version: 0.1.0
links:
- name: zookeeper
  title: ZooKeeper
  required: true
  selectors:
  - type: datastore
    labels:
    - zookeeper

tokens:
- name: password
  generate:
    regex: '[0-9a-z-]{32}'

volumes:
- name: data
  title: Data
  optional: true
  size: 5
  helm:
    labels: persistence.labels
    values:
    - name: persistence.enabled
      value: true
    - name: persistence.size
      value: '{{volumes.data.size}}Gi'

actions:
- name: init
  title: Run init
  args:
  - make
  - init
  - 'host={{service.host}}'
  - -f
  - /usr/local/bin/actions.mk
  type: post_deploy
workloads:
- id: main
  kind: statefulset
  primary: true
  containers:
  - name: solr
    image: wodby/solr
    env:
    - name: ZK_HOST
      value: '{{links.zookeeper.host}}'
    - name: SOLR_CLOUD_PASSWORD
      value: '{{password}}'
      secret: true
# make sure Kubernetes env var overridden with correct value to not break health check
    - name: SOLR_PORT
      value: '8983'

    helm:
      resources: resources
      env: envVars
      mounts: extraVolumeMounts
  helm:
    labels: podLabels
    annotations: podAnnotations
    volumes: extraVolumes
