name: solr
icon: solr
type: search
title: Solr
hostname: solr
operators:
- service: solr-operator
containers:
- name: solr
  image: wodby/solr
  ports:
  - name: solr
    number: 8983
    type: tcp
options:
- version: '9.5.0'
scalable: false
labels:
- solr
operators:
- name: operator
  title: Solr Operator
  service: solr-operator

helm:
  name: apache-solr
  source: https://solr.apache.org/charts
  chart: apache-solr/solr
  version: v0.8.0  

volumes:
- name: data
  title: Data
  path: /opt/solr/server/solr
  size: 10
