name: solr
icon: solr
type: search
title: Solr
hostname: solr
containers:
- name: solr
  image: solr
  ports:
  - name: solr
    number: 80
    type: http
    main: true    
options:
- version: '9'
  tag: '9.6.0'
labels:
- solr

kubernetes:
  infrastructure:
  - name: operator
    title: Solr Operator
    service: solr-operator
    version: 'v0.8.0'

helm:
  name: apache-solr
  source: https://solr.apache.org/charts
  chart: apache-solr/solr
  version: v0.8.0
  configurations:
  - name: solr
    labels: statefulSetOptions.labels
    annotations: statefulSetOptions.annotations
    env: podOptions.envVars
    ingresses: 
    - name: common
      service: '{{service.name}}-solrcloud-common'
    resources: podOptions.resources
  values: 
  - name: 'zk.address'
    value: '{{links.zookeeper.host}}'
  - name: solrOptions.security.authenticationType
    value: Basic
  - name: solrOptions.security.basicAuthSecret
    value: '{{secrets.auth.name}}'
  - name: solrOptions.security.bootstrapSecurityJson.name
    value: '{{secrets.security.name}}'
  - name: solrOptions.security.bootstrapSecurityJson.key
    value: 'security.json'

links:
- name: zookeeper
  title: ZooKeeper
  required: true
  selectors:
  - type: datastore
    labels:
    - zookeeper

secrets:
- name: auth
  type: kubernetes.io/basic-auth
  data:
  - key: username
    value: solr
  - key: password
    value: '{{password}}'
- name: security  
  data:
  - key: security.json
    value: |
      {
        "authentication":{
          "class":"solr.BasicAuthPlugin",
          "credentials":{"solr":"{{wodby_solr_hash_password}}"},
          "blockUnknown": "true"
        },
        "authorization":{
          "class":"solr.RuleBasedAuthorizationPlugin",
          "permissions":[{
            "name":"security-edit",
            "role":"admin"
          }],
          "user-role":{"solr":"admin"}
        }
      }

tokens:
- name: password
  generate:
    regex: '[0-9a-z-]{32}'  

volumes:
- name: data
  title: Data
  optional: true
  size: 5
  helm: 
    values:
    - name: dataStorage.type
      value: persistent
    - name: dataStorage.capacity
      value: '{{volumes.data.size}}Gi'
    - name: dataStorage.persistent.reclaimPolicy
      value: Delete

